spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edtech_db
    username: edtech_user
    password: edtech_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

edtech:
  email:
    provider: mock
  media:
    storage-type: LOCAL
  stripe:
    secret-key: sk_test_dummy
    webhook-secret: whsec_test_dummy

logging:
  level:
    com.edtech: DEBUG
